spring:
  application:
    name: football
server:
  port: 9003
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  security:
    enabled: false
